version: '3.4'

services:
  backend:
    image: backend
    command: gunicorn --bind 0.0.0.0:3001 main:app --reload
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - STACK_OVERFLOW_ANSWERS_FILTER=!6VvPDzQywl)na
      - STACK_EXCHANGE_API_KEY=4dKjXjKDIyAW)*3knpuW3g((
      - MODEL_UPDATE_INTERVAL_SECONDS=86400
      - SCORE_THRESHOLD=0.1
    ports:
      - 3001:3001
    volumes:
      - .:/app
